export const mock_products: any[] = [
  {
    id: 1,
    title: "Brown eggs",
    type: "dairy",
    description: "Raw organic brown eggs in a basket",
    filename: "0.jpg",
    height: 600,
    width: 400,
    price: 4.1,
    rating: 4,
  },
  {
    id: 2,
    title: "Fresh stawberry",
    type: "fruit",
    description: "Sweet fresh stawberry on the wooden table",
    filename: "1.jpg",
    height: 450,
    width: 299,
    price: 5.45,
    rating: 4,
  },
  {
    id: 3,
    title: "Fresh blueberry",
    type: "fruit",
    description: "Sweet fresh blueberry on the wooden table",
    filename: "1.jpg",
    height: 450,
    width: 299,
    price: 5.45,
    rating: 4,
  },
  {
    id: 4,
    title: "Asparagus",
    type: "vegetable",
    description: "Asparagus with ham on the wooden table",
    filename: "2.jpg",
    height: 450,
    width: 299,
    price: 2.95,
    rating: 3,
  },
  {
    id: 5,
    title: "Green smoothie",
    type: "dairy",
    description: "Glass of green smoothie with quail egg's yolk, served with cocktail tube, green apple and baby spinach leaves over tin surface.",
    filename: "3.jpg",
    height: 600,
    width: 399,
    price: 7.68,
    rating: 4,
  },
  {
    id: 6,
    title: "Tomatoes",
    type: "vegetable",
    description: "Raw tomatoes on the wooden table",
    filename: "4.jpg",
    height: 450,
    width: 299,
    price: 2.11,
    rating: 2,
  },
  {
    id: 7,
    title: "Raw beef",
    type: "meat",
    description: "Raw beef from steak on the wooden table",
    filename: "5.jpg",
    height: 450,
    width: 299,
    price: 22.35,
    rating: 4,
  },
  {
    id: 8,
    title: "Chicken breast",
    type: "meat",
    description: "Chicken breast roasted on the wooden table",
    filename: "6.jpg",
    height: 450,
    width: 299,
    price: 18.76,
    rating: 4,
  },
  {
    id: 9,
    title: " Bell pepper",
    type: "vegetable",
    description: "Bell pepper with red on the wooden table",
    filename: "7.jpg",
    height: 450,
    width: 299,
    price: 2.35,
    rating: 4,

  },
  {
    id: 10,
    title: "Mushrooms",
    type: "vegetable",
    description: "Mushrooms on the wooden table",
    filename: "8.jpg",
    height: 450,
    width: 299,
    price: 3.99,
    rating: 4,
  },
  {
    id: 11,
    title: "Cow milk",
    type: "dairy",
    description: "Raw cow's milk in a basket",
    filename: "9.jpg",
    height: 450,
    width: 299,
    price: 2.99,
    rating: 4,
  },
  {
    id: 12,
    title: "Pineapple",
    type: "fruit",
    description: "Sweet fresh pineapple on the wooden table",
    filename: "10.jpg",
    height: 450,
    width: 299,
    price: 2.55,
    rating: 4,
  },
  {
    id: 13,
    title: "Salmon",
    type: "fish",
    description: "Raw salmon steak with vegetables on the wooden table",
    filename: "11.jpg",
    height: 450,
    width: 299,
    price: 12.11,
    rating: 4,
  },
  {
    id: 14,
    title: "Tuna steak",
    type: "fish",
    description: "Raw tuna steak with vegetables on the wooden table",
    filename: "12.jpg",
    height: 450,
    width: 299,
    price: 21.99,
    rating: 4,
  },
  {
    id: 15,
    title: "Kale",
    type: "vegetable",
    description: "Kale with garlic and red on the wooden table",
    filename: "13.jpg",
    height: 450,
    width: 299,
    price: 3.99,
    rating: 4,
  },
  {
    id: 16,
    title: "Red potatoes",
    type: "vegetable",
    description: "Red potatoes on the wooden table",
    filename: "14.jpg",
    height: 450,
    width: 299,
    price: 5.55,
    rating: 4,
  },
  {
    id: 17,
    title: "Orange",
    type: "fruit",
    description: "Orange on the wooden table",
    filename: "15.jpg",
    height: 450,
    width: 299,
    price: 2.99,
    rating: 4,
  },
  {
    id: 18,
    title: "Pear",
    type: "fruit",
    description: "Pear on the wooden table",
    filename: "16.jpg",
    height: 450,
    width: 299,
    price: 2.99,
    rating: 4,
  },
  
  
  
];

export const mock_users: any[] = [
  {
    id: 1,
    name: "Anna Doe",
    email: "annaddd@gmail.com",
    password: "anna",
  },
  {
    id: 2,
    name: "John Doe",
    email: "johnny@gmail.com",
    password: "john",
  },
  {
    id: 3,
    name: "Jane Doe",
    email: "jane_doe@gmail.com",
    password: "jane",
  },
];
